---

- name: Prepare step for nginx
  block:
    - name: Find out if it is baremetal or vm
      command: "systemd-detect-virt"
      register: virt
      ignore_errors: true


    - name: create directory for nginx files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root

